In [1]:
import numpy as np
import time
import os

# Task 1.4.1: Given a 6x6 matrix of random integers 1-100, extract all elements that are divisible by both 3 and 5.
mat = np.random.randint(1, 101, size=(6, 6))
res = mat[(mat % 3 == 0) & (mat % 5 == 0)]
print(mat)
print("Divisible by 3 and 5:", res)

[[79  3 70 58 36 38]
 [ 7 51 75 44 98 71]
 [25  5  6 64 62 52]
 [61 14 67 50 37 12]
 [65 66 45 76 61 49]
 [ 1 19 53 80 78 65]]
Divisible by 3 and 5: [75 45]


In [2]:
# Task 1.4.2: Use np.where to replace all values below the mean of an array with 0 and above with 1 (binarise).
arr = np.random.randint(1, 100, size=15)
m = np.mean(arr)
binarised = np.where(arr < m, 0, 1)
print("original:", arr)
print("mean:", m)
print("binarised:", binarised)

original: [43 94 98 61 51 50 20 94 14 21 42 47 88 77 13]
mean: 54.2
binarised: [0 1 1 1 0 0 0 1 0 0 0 0 1 1 0]


In [3]:
# Task 1.4.3: Use np.ix_ to extract a 3x3 sub-matrix from rows [1,3,4] and columns [0,2,4] of a 5x5 array.
matrix_5x5 = np.random.randint(1, 50, size=(5, 5))
rows = [1, 3, 4]
cols = [0, 2, 4]
sub_mat = matrix_5x5[np.ix_(rows, cols)]
print("5x5 matrix:\n", matrix_5x5)
print("sub matrix:\n", sub_mat)

5x5 matrix:
 [[39 42 46 36 49]
 [25  9 15 47  1]
 [36 40 35 21 13]
 [47  3 23 45  9]
 [24 14 30 12 13]]
sub matrix:
 [[25 15  1]
 [47 23  9]
 [24 30 13]]


In [4]:
# Task 1.4.4: Sort a 4x4 random matrix row-wise and column-wise separately (without loops).
mat_4x4 = np.random.randint(1, 100, (4, 4))
row_sort = np.sort(mat_4x4, axis=1)
col_sort = np.sort(mat_4x4, axis=0)
print("original:\n", mat_4x4)
print("row sorted:\n", row_sort)
print("col sorted:\n", col_sort)

original:
 [[12 58  7 37]
 [75  7 56 75]
 [39 49 58 21]
 [73 63 91 82]]
row sorted:
 [[ 7 12 37 58]
 [ 7 56 75 75]
 [21 39 49 58]
 [63 73 82 91]]
col sorted:
 [[12  7  7 21]
 [39 49 56 37]
 [73 58 58 75]
 [75 63 91 82]]


In [5]:
# Task 1.4.5: Use np.select to classify 15 random scores into: 'A'(>=85), 'B'(>=70), 'C'(>=55), 'D'(>=40), 'F'(below 40).
scores = np.random.randint(20, 100, 15)
conditions = [
    scores >= 85,
    scores >= 70,
    scores >= 55,
    scores >= 40
]
values = ['A', 'B', 'C', 'D']
grades = np.select(conditions, values, default='F')
print("Scores:", scores)
print("Grades:", grades)

Scores: [83 49 64 39 54 93 40 44 93 93 61 29 38 39 86]
Grades: ['B' 'D' 'C' 'F' 'D' 'A' 'D' 'D' 'A' 'A' 'C' 'F' 'F' 'F' 'A']


In [6]:
# Task 2.2.1: Add [1, 2, 3, 4] to every row of a (5,4) matrix and subtract [10,20,30,40,50] from every column.
m = np.zeros((5, 4))
row_add = np.array([1, 2, 3, 4])
col_sub = np.array([10, 20, 30, 40, 50])[:, np.newaxis]
ans = m + row_add - col_sub
print(ans)

[[ -9.  -8.  -7.  -6.]
 [-19. -18. -17. -16.]
 [-29. -28. -27. -26.]
 [-39. -38. -37. -36.]
 [-49. -48. -47. -46.]]


In [7]:
# Task 2.2.2: Normalise each column of a 6x4 random matrix to have mean=0 and std=1 using broadcasting.
data = np.random.randint(10, 100, (6, 4)).astype(float)
col_mean = np.mean(data, axis=0)
col_std = np.std(data, axis=0)
normalised = (data - col_mean) / col_std
print("normalised data:\n", normalised)
print("mean of cols:", np.mean(normalised, axis=0))
print("std of cols:", np.std(normalised, axis=0))

normalised data:
 [[-1.02182923 -1.54581402 -1.40378619  0.38776823]
 [-0.08963414  0.32758973 -0.49672434  0.55884246]
 [ 0.91426826 -1.1158525  -0.43193421 -1.4940482 ]
 [ 1.70304872  1.06466661  0.02159671  0.42198308]
 [-0.95012192  1.03395507  0.47512763 -1.1861146 ]
 [-0.55573169  0.23545512  1.8357204   1.31156903]]
mean of cols: [ 1.85037171e-17 -8.32667268e-17  1.11022302e-16  7.40148683e-17]
std of cols: [1. 1. 1. 1.]


In [8]:
# Task 2.2.3: Build a distance matrix: given 5 points on a number line, create a 5x5 matrix where entry [i,j] = |points[i] - points[j]|. Use broadcasting, no loops.
points = np.array([1, 4, 8, 15, 22])
dist_mat = np.abs(points[:, np.newaxis] - points)
print("points:", points)
print("distance matrix:\n", dist_mat)

points: [ 1  4  8 15 22]
distance matrix:
 [[ 0  3  7 14 21]
 [ 3  0  4 11 18]
 [ 7  4  0  7 14]
 [14 11  7  0  7]
 [21 18 14  7  0]]


In [9]:
# Task 3.3.1: Create a random 3x3 matrix A. Verify A @ inv(A) is approx identity using np.allclose.
A = np.random.rand(3, 3)
A_inv = np.linalg.inv(A)
I_approx = A @ A_inv
print("Is it close to identity?", np.allclose(I_approx, np.eye(3)))

Is it close to identity? True


In [10]:
# Task 3.3.2: Solve the system: 2x+y=5, x+3y=10 using np.linalg.solve. Verify your answer.
coeff = np.array([[2, 1], [1, 3]])
b = np.array([5, 10])
ans = np.linalg.solve(coeff, b)
print("x and y:", ans)
print("verify:", coeff @ ans)

x and y: [1. 3.]
verify: [ 5. 10.]


In [11]:
# Task 3.3.3: Generate a symmetric matrix S = A.T @ A. Compute its eigenvalues and verify they are all non-negative.
A_mat = np.random.rand(4, 4)
S = A_mat.T @ A_mat
vals, vecs = np.linalg.eig(S)
print("eigenvalues:", vals)
print("are all non-negative?", np.all(vals >= -1e-10))

eigenvalues: [3.55063727 0.01143491 0.23262842 0.45718088]
are all non-negative? True


In [12]:
# Task 3.3.4: Compute the dot product of two random unit vectors (normalise with np.linalg.norm first). Interpret the result.
v1 = np.random.rand(3)
v2 = np.random.rand(3)
v1_norm = v1 / np.linalg.norm(v1)
v2_norm = v2 / np.linalg.norm(v2)
dot_val = np.dot(v1_norm, v2_norm)
print("dot product:", dot_val)
# the dot product of two unit vectors gives the cosine of the angle between them.

dot product: 0.5696413943088265


In [13]:
# Task 4.3.1: Given a 1D array of 20 random integers, find the indices of the 5 smallest and 5 largest values without fully sorting.
arr = np.random.randint(1, 100, 20)
small_idx = np.argpartition(arr, 5)[:5]
large_idx = np.argpartition(arr, -5)[-5:]
print("array:", arr)
print("5 smallest indices:", small_idx, "values:", arr[small_idx])
print("5 largest indices:", large_idx, "values:", arr[large_idx])

array: [81 21 38 75 54 71 89  4  4 90 86 24 57 85 42 66 17 55 90 85]
5 smallest indices: [ 7  8 16 11  1] values: [ 4  4 17 24 21]
5 largest indices: [13 10  6 18  9] values: [85 86 89 90 90]


In [14]:
# Task 4.3.2: Sort a 5x5 matrix so each row is sorted ascending and each column is sorted ascending.
m = np.random.randint(1, 100, (5, 5))
# sort rows first
m_sorted = np.sort(m, axis=1)
# then sort columns
m_sorted = np.sort(m_sorted, axis=0)
print(m_sorted)

[[10 13 34 44 45]
 [15 21 57 65 82]
 [20 47 58 73 85]
 [30 52 64 80 86]
 [40 64 80 86 86]]


In [15]:
# Task 4.3.3: From two random integer arrays of size 15 (range 1-20), find common elements, elements only in A, and elements only in B.
A = np.random.randint(1, 21, 15)
B = np.random.randint(1, 21, 15)
print("A:", A)
print("B:", B)
print("common:", np.intersect1d(A, B))
print("only in A:", np.setdiff1d(A, B))
print("only in B:", np.setdiff1d(B, A))

A: [ 7 10 15  2  8  8 16  5  2 10 13  1 17  7  9]
B: [16 17 13  3 13  9 18  4 20  4  7  5 17 10  7]
common: [ 5  7  9 10 13 16 17]
only in A: [ 1  2  8 15]
only in B: [ 3  4 18 20]


In [16]:
# Task 5.3.1: Create a 20x5 random float array, save it as both .npy and .csv, reload both, and confirm they are equal using np.allclose.
data = np.random.rand(20, 5)
np.save('my_data.npy', data)
np.savetxt('my_data.csv', data, delimiter=',')

load_npy = np.load('my_data.npy')
load_csv = np.loadtxt('my_data.csv', delimiter=',')

print("same as npy?", np.allclose(data, load_npy))
print("same as csv?", np.allclose(data, load_csv))

same as npy? True
same as csv? True


In [17]:
# Task 5.3.2: Simulate a dataset of 50 students with 4 subject marks. Save to CSV. Reload and compute: class topper, subject-wise averages, and students scoring below 50 in any subject.
marks = np.random.randint(30, 100, (50, 4))
np.savetxt('student_marks.csv', marks, delimiter=',')

loaded_marks = np.loadtxt('student_marks.csv', delimiter=',')
totals = loaded_marks.sum(axis=1)
topper = np.argmax(totals)
sub_avg = loaded_marks.mean(axis=0)
below_50 = np.any(loaded_marks < 50, axis=1)
fail_count = np.sum(below_50)

print("topper student index:", topper)
print("subject averages:", sub_avg)
print("total students scoring below 50 in any sub:", fail_count)

topper student index: 39
subject averages: [64.62 63.56 68.36 64.94]
total students scoring below 50 in any sub: 35


In [18]:
# Task 6.3.1: Rewrite the following loop using vectorisation: result = []; for i in range(len(x)): result.append(x[i]**2 + 2*x[i] + 1). Benchmark both.
x = np.random.rand(1000000)

t1 = time.perf_counter()
res_loop = []
for i in range(len(x)):
    res_loop.append(x[i]**2 + 2*x[i] + 1)
t2 = time.perf_counter()
print(f"loop took {t2-t1:.4f} secs")

t3 = time.perf_counter()
res_vec = x**2 + 2*x + 1
t4 = time.perf_counter()
print(f"vectorised took {t4-t3:.4f} secs")

loop took 0.5676 secs
vectorised took 0.0156 secs


In [19]:
# Task 6.3.2: Use np.einsum to compute the outer product of two vectors and verify it matches np.outer.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
outer_ein = np.einsum('i,j->ij', a, b)
outer_np = np.outer(a, b)
print("match?", np.array_equal(outer_ein, outer_np))

match? True


In [20]:
# Task 6.3.3: Generate a float32 and float64 array of 1M elements. Compare memory usage and computation speed for squaring each.
f32 = np.random.rand(1000000).astype(np.float32)
f64 = np.random.rand(1000000).astype(np.float64)

print(f"f32 memory: {f32.nbytes / (1024*1024):.2f} MB")
print(f"f64 memory: {f64.nbytes / (1024*1024):.2f} MB")

t1 = time.perf_counter()
_ = f32 ** 2
t2 = time.perf_counter()

t3 = time.perf_counter()
_ = f64 ** 2
t4 = time.perf_counter()

print(f"f32 square time: {t2-t1:.4f}s")
print(f"f64 square time: {t4-t3:.4f}s")

f32 memory: 3.81 MB
f64 memory: 7.63 MB
f32 square time: 0.0017s
f64 square time: 0.0038s
